/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-06-07 16:27:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/toshiba/Desktop/ATSEApp/ATSEApp/dev/WEB-INF/lib/kendo-taglib-2019.3.1023.jar!/META-INF/taglib.tld", Long.valueOf(1571791588000L));
    _jspx_dependants.put("jar:file:/C:/Users/toshiba/Desktop/ATSEApp/ATSEApp/dev/WEB-INF/lib/struts2-core-2.5.20.jar!/META-INF/struts-tags.tld", Long.valueOf(1547013768000L));
    _jspx_dependants.put("/WEB-INF/lib/kendo-taglib-2019.3.1023.jar", Long.valueOf(1575989688000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.20.jar", Long.valueOf(1548061330000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkendo_005fnotification_0026_005fstacking_005fname_005fautoHideAfter;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplates;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkendo_005fnotification_0026_005fstacking_005fname_005fautoHideAfter = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplates = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkendo_005fnotification_0026_005fstacking_005fname_005fautoHideAfter.release();
    _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplates.release();
    _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-7\" id=\"logoPart\">\n");
      out.write("\t\t\t\t<div class=\"state-name\" style=\"cursor: pointer;\" onclick=\"window.location = 'home.action';\">Academic Thesaurus Search Engine</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<br>\n");
      out.write("\t</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- KENDO : Notifications -->\n");
      if (_jspx_meth_kendo_005fnotification_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<script id=\"errorTemplate\" type=\"text/x-kendo-template\">        \n");
      out.write("    <div class=\"wrong\">\n");
      out.write("    \t<img src=\"images/error-icon.png\" />\n");
      out.write("        <h3>Error</h3>\n");
      out.write("        <p>#= message #</p>\n");
      out.write("    </div>\n");
      out.write("</script>\n");
      out.write("<script id=\"successTemplate\" type=\"text/x-kendo-template\" >\n");
      out.write("    <div class=\"success\">\n");
      out.write("    \t<img src=\"images/success-icon.png\" />\n");
      out.write("\t\t<h3>Success</h3>\n");
      out.write("    \t<p>#= message #</p>\n");
      out.write("    </div>\n");
      out.write("</script>\n");
      out.write("<script id=\"infoTemplate\" type=\"text/x-kendo-template\" >\n");
      out.write("    <div class=\"info\">\n");
      out.write("\t\t<p style=\"padding: 10px;\">#= message #</p>\n");
      out.write("\t\t<hr style=\"margin: 10px 0px;\"/>\n");
      out.write("\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t<button type=\"button\" class='btn btn-primary confirm-yes-btn'>Ok</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script id=\"confirmDeleteTemplate\" type=\"text/x-kendo-template\" >\n");
      out.write("    <p style=\"padding: 10px;\">#= message #</p>\n");
      out.write("\t<hr style=\"margin: 10px 0px;\"/>\n");
      out.write("\t<div class=\"pull-right\">\n");
      out.write("\t\t<button type=\"button\" class='btn btn-primary confirm-yes-btn'>Yes</button>\n");
      out.write("\t\t<button type=\"button\" class='btn btn-default confirm-no-btn'>No</button>\n");
      out.write("\t</div>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tvar notification = $(\"#notification\").kendoNotification({\n");
      out.write("\t    autoHideAfter: 3000,\n");
      out.write("\t    stacking: \"down\",\n");
      out.write("\t    show: onShow,\n");
      out.write("\t    templates: [{\n");
      out.write("\t        type: \"error\",\n");
      out.write("\t        template: $(\"#errorTemplate\").html()\n");
      out.write("\t    }, {\n");
      out.write("\t        type: \"success\",\n");
      out.write("\t        template: $(\"#successTemplate\").html()\n");
      out.write("\t    }, {\n");
      out.write("\t        type: \"info\",\n");
      out.write("\t        template: $(\"#infoTemplate\").html()\n");
      out.write("\t    }]\n");
      out.write("\t\n");
      out.write("\t}).data(\"kendoNotification\");\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction onShow(e) {\n");
      out.write("        if (e.sender.getNotifications().length == 1) {\n");
      out.write("            var element = e.element.parent(),\n");
      out.write("                eWidth = element.width(),\n");
      out.write("                eHeight = element.height(),\n");
      out.write("                wWidth = $(window).width(),\n");
      out.write("                wHeight = $(window).height(),\n");
      out.write("                newTop, newLeft;\n");
      out.write("            \n");
      out.write("            newLeft = Math.floor(wWidth - eWidth-50);\n");
      out.write("            newTop = Math.floor(eHeight-10);\n");
      out.write("\n");
      out.write("            e.element.parent().css({top: newTop, left: newLeft});\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kendo_005fnotification_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kendo:notification
    com.kendoui.taglib.NotificationTag _jspx_th_kendo_005fnotification_005f0 = (com.kendoui.taglib.NotificationTag) _005fjspx_005ftagPool_005fkendo_005fnotification_0026_005fstacking_005fname_005fautoHideAfter.get(com.kendoui.taglib.NotificationTag.class);
    boolean _jspx_th_kendo_005fnotification_005f0_reused = false;
    try {
      _jspx_th_kendo_005fnotification_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kendo_005fnotification_005f0.setParent(null);
      // /tiles/home/header.jsp(15,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_005f0.setName("notification");
      // /tiles/home/header.jsp(15,0) name = autoHideAfter type = float reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_005f0.setAutoHideAfter(3000.0f);
      // /tiles/home/header.jsp(15,0) name = stacking type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_005f0.setStacking("down");
      int _jspx_eval_kendo_005fnotification_005f0 = _jspx_th_kendo_005fnotification_005f0.doStartTag();
      if (_jspx_eval_kendo_005fnotification_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_kendo_005fnotification_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_kendo_005fnotification_005f0);
        }
        do {
          out.write('\n');
          out.write('	');
          if (_jspx_meth_kendo_005fnotification_002dtemplates_005f0(_jspx_th_kendo_005fnotification_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_kendo_005fnotification_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_kendo_005fnotification_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_kendo_005fnotification_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkendo_005fnotification_0026_005fstacking_005fname_005fautoHideAfter.reuse(_jspx_th_kendo_005fnotification_005f0);
      _jspx_th_kendo_005fnotification_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kendo_005fnotification_005f0, _jsp_getInstanceManager(), _jspx_th_kendo_005fnotification_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kendo_005fnotification_002dtemplates_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_kendo_005fnotification_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kendo:notification-templates
    com.kendoui.taglib.notification.TemplatesTag _jspx_th_kendo_005fnotification_002dtemplates_005f0 = (com.kendoui.taglib.notification.TemplatesTag) _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplates.get(com.kendoui.taglib.notification.TemplatesTag.class);
    boolean _jspx_th_kendo_005fnotification_002dtemplates_005f0_reused = false;
    try {
      _jspx_th_kendo_005fnotification_002dtemplates_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kendo_005fnotification_002dtemplates_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_kendo_005fnotification_005f0);
      int _jspx_eval_kendo_005fnotification_002dtemplates_005f0 = _jspx_th_kendo_005fnotification_002dtemplates_005f0.doStartTag();
      if (_jspx_eval_kendo_005fnotification_002dtemplates_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_kendo_005fnotification_002dtemplates_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_kendo_005fnotification_002dtemplates_005f0);
        }
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_kendo_005fnotification_002dtemplate_005f0(_jspx_th_kendo_005fnotification_002dtemplates_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_kendo_005fnotification_002dtemplate_005f1(_jspx_th_kendo_005fnotification_002dtemplates_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_kendo_005fnotification_002dtemplate_005f2(_jspx_th_kendo_005fnotification_002dtemplates_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_kendo_005fnotification_002dtemplates_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_kendo_005fnotification_002dtemplates_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_kendo_005fnotification_002dtemplates_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplates.reuse(_jspx_th_kendo_005fnotification_002dtemplates_005f0);
      _jspx_th_kendo_005fnotification_002dtemplates_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kendo_005fnotification_002dtemplates_005f0, _jsp_getInstanceManager(), _jspx_th_kendo_005fnotification_002dtemplates_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kendo_005fnotification_002dtemplate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_kendo_005fnotification_002dtemplates_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kendo:notification-template
    com.kendoui.taglib.notification.TemplateTag _jspx_th_kendo_005fnotification_002dtemplate_005f0 = (com.kendoui.taglib.notification.TemplateTag) _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.get(com.kendoui.taglib.notification.TemplateTag.class);
    boolean _jspx_th_kendo_005fnotification_002dtemplate_005f0_reused = false;
    try {
      _jspx_th_kendo_005fnotification_002dtemplate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kendo_005fnotification_002dtemplate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_kendo_005fnotification_002dtemplates_005f0);
      // /tiles/home/header.jsp(17,2) name = type type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f0.setType("error");
      // /tiles/home/header.jsp(17,2) name = template type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f0.setTemplate("errorTemplate");
      int _jspx_eval_kendo_005fnotification_002dtemplate_005f0 = _jspx_th_kendo_005fnotification_002dtemplate_005f0.doStartTag();
      if (_jspx_th_kendo_005fnotification_002dtemplate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.reuse(_jspx_th_kendo_005fnotification_002dtemplate_005f0);
      _jspx_th_kendo_005fnotification_002dtemplate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kendo_005fnotification_002dtemplate_005f0, _jsp_getInstanceManager(), _jspx_th_kendo_005fnotification_002dtemplate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kendo_005fnotification_002dtemplate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_kendo_005fnotification_002dtemplates_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kendo:notification-template
    com.kendoui.taglib.notification.TemplateTag _jspx_th_kendo_005fnotification_002dtemplate_005f1 = (com.kendoui.taglib.notification.TemplateTag) _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.get(com.kendoui.taglib.notification.TemplateTag.class);
    boolean _jspx_th_kendo_005fnotification_002dtemplate_005f1_reused = false;
    try {
      _jspx_th_kendo_005fnotification_002dtemplate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_kendo_005fnotification_002dtemplate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_kendo_005fnotification_002dtemplates_005f0);
      // /tiles/home/header.jsp(18,2) name = type type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f1.setType("success");
      // /tiles/home/header.jsp(18,2) name = template type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f1.setTemplate("successTemplate");
      int _jspx_eval_kendo_005fnotification_002dtemplate_005f1 = _jspx_th_kendo_005fnotification_002dtemplate_005f1.doStartTag();
      if (_jspx_th_kendo_005fnotification_002dtemplate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.reuse(_jspx_th_kendo_005fnotification_002dtemplate_005f1);
      _jspx_th_kendo_005fnotification_002dtemplate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kendo_005fnotification_002dtemplate_005f1, _jsp_getInstanceManager(), _jspx_th_kendo_005fnotification_002dtemplate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kendo_005fnotification_002dtemplate_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_kendo_005fnotification_002dtemplates_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kendo:notification-template
    com.kendoui.taglib.notification.TemplateTag _jspx_th_kendo_005fnotification_002dtemplate_005f2 = (com.kendoui.taglib.notification.TemplateTag) _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.get(com.kendoui.taglib.notification.TemplateTag.class);
    boolean _jspx_th_kendo_005fnotification_002dtemplate_005f2_reused = false;
    try {
      _jspx_th_kendo_005fnotification_002dtemplate_005f2.setPageContext(_jspx_page_context);
      _jspx_th_kendo_005fnotification_002dtemplate_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_kendo_005fnotification_002dtemplates_005f0);
      // /tiles/home/header.jsp(19,2) name = type type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f2.setType("info");
      // /tiles/home/header.jsp(19,2) name = template type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kendo_005fnotification_002dtemplate_005f2.setTemplate("infoTemplate");
      int _jspx_eval_kendo_005fnotification_002dtemplate_005f2 = _jspx_th_kendo_005fnotification_002dtemplate_005f2.doStartTag();
      if (_jspx_th_kendo_005fnotification_002dtemplate_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkendo_005fnotification_002dtemplate_0026_005ftype_005ftemplate_005fnobody.reuse(_jspx_th_kendo_005fnotification_002dtemplate_005f2);
      _jspx_th_kendo_005fnotification_002dtemplate_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kendo_005fnotification_002dtemplate_005f2, _jsp_getInstanceManager(), _jspx_th_kendo_005fnotification_002dtemplate_005f2_reused);
    }
    return false;
  }
}
